version: '3.3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  web-idealmart:
    container_name: web-idealmart
    image: idealmart-web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-idealmart.rule=Host(`idealmart.ca`)
      - traefik.http.routers.web-idealmart.tls=true
      - traefik.http.routers.web-idealmart.tls.certresolver=lets-encrypt
      - traefik.http.services.web-idealmart.loadbalancer.server.port=80
    networks:
      - web
      - internal
