version: '3.3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  web-idealmart:
    container_name: web-idealmart
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-idealmart.rule=Host(`idealmart.ca`)
      - traefik.http.routers.web-idealmart.tls=true
      - traefik.http.routers.web-idealmart.tls.certresolver=lets-encrypt
      - traefik.http.services.web-idealmart.loadbalancer.server.port=3000
    networks:
      - web
      - internal
