version: '3.3'
networks:
  web:
    external: true
  internal:
    external: false 

services:
  web-idealmart:
    container_name: web-idealmart
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.http.routers.web-idealmart.rule=Host(`idealmart.ca`)
      - traefik.http.routers.web-idealmart.tls=true
      - traefik.http.routers.web-idealmart.tls.certresolver=lets-encrypt
      - traefik.port=3000 
    networks:
      - web
      - internal 
  # web-wk14u:
  #   container_name: web-wk14u
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   labels:
  #     - traefik.http.routers.web-wk14u.rulst(`customer-uat.vidfin.com`)
  #     - traefik.http.routers.web-wk14u.tlse
  #     - traefik.http.routers.web-wk14u.tlstresolver=lets-encrypt
  #     - traefik.port=3000 
  #   environment:
  #     - NEXT_PUBLIC_BASE_URL=https://uat-api.vidfin.com/api
  #     - NODE_ENV=development
  #   networks:
  #     - web
  #     - internal 